os: linux # => 1
language: python # => 2
python: # => 3
  - "3.6"
  - "3.7"
  - "3.8"
env: # => 5
  -DJANGO=3.2 DB=sqlite
install: # => 6
  - pip install -r requirements.txt
script: # => 7
  - python BMI_calc/manage.py test