language: python
# python versions
python:
  - "3.8"
env:
  -DJANGO=4.1.7
# install requirements
install:
  - pip install -r requirements.txt
  - pip install coveralls
# To run tests
script:
  - coverage run --source=calc manage.py test
# send coverage report to coveralls
after_success:
  coveralls
